### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by orlink** [vackosar/keras-punctuator#2]
Thanks for the nice work, Vaclav!  

From what I am able to understand from perusing the code, sequences are left-padded to the window size (=30), but punctuation is only trained/predicted for the middle word of the window. Does that mean that the whole model is able to predict punctuation in any text after the 15th word? 

Are GloVe embedings required (at least for good performance)?

Would the code work for non-ASCII languages? I noticed a byte array at one place in the code.

Thanks in advance.

**Comment by vackosar** [comment]
1 - The punctuation is predicted for all places by sliding the window across the text. Padding is applied to detect also boundary words, such that all words have a prediction.
2 - It may possibly work without them, but with larger model. Thanks to Glove one can have smaller model and train shorter. I havent verified that though.
3 - Glove transforms words to vectors. If it supports non ascii there will be no problem. To speed up a projection on most common words 20k is used, where words are mapped to integer. This may be the byte array you saw there.
