### ISSUE TITLE
Model Output

### ISSUE THREAD

**Issue by BoPengGit** [vackosar/keras-punctuator#4]
Hi Vackosar, 

For this model, the input data is a sequence of 30 words (tokens) without punctuation, and what is the output for the ConvNet?

Is it 30 numbers where each number is a number that represents either non punctuation or punctuation and the specific type or what is the output for the Conv net?

Thanks!

**Comment by vackosar** [comment]
The net predicts whether there is a punctuation after 15th word. There may be bug however where it predicts rather after 16th word, but that is not of much importance.

**Comment by BoPengGit** [comment]
Hi vackosar,

Thanks for the response. Good job on the project.

So there is a sliding window to predict the 15th word punctuation? 

Thanks for the help.

**Comment by vackosar** [comment]
yes
