### ISSUE TITLE
 Problem with freeze()

### ISSUE THREAD

**Issue by mygod1980** [vackosar/keras-punctuator#8]
Hi Vaclav! Thank you for your interesting project!

I`m trying to build a model on my data, but when freeze() runs there is an error (I put it under ==)
I have python 3.6.5 with tensorflow 1.7.0 and Keras 2.1.5 on Windows 10.
Can you suggest how to fix it? I tried to downgrade tersorflow, no effect.
Thank you!

=======
 File "C:\Users\mygod\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: **Tensor Tensor("Placeholder:0", shape=(20000, 100), dtype=float32) is not an element of this graph.**

During handling of the above exception, another exception occurred:

TypeError: **Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(20000, 100), dtype=float32) is not an element of this graph.**

**Comment by vackosar** [comment]
I had lots of issues with freezing as it seemed to be using unstable API. If you can, just don't do it at all (if you dont need to use the trained model.) If you do, try to read the latest docs a new and reimplement it.

If you make it work, you can submit a pull request here and share your improvement!
